/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
       // System.out.println(new App().getGreeting());
        StandardCalculator calc=new StandardCalculator();
        
        calc.add(1,2);
        System.out.println(calc.getResult());

        
StandardCalculator c = new StandardCalculator();

c.add(1.5, 2.5);
System.out.println(c.getResult());

/* 
StandardCalculator c1 = new StandardCalculator();

c1.add(Double.MAX_VALUE, 1.0);

c1.printResult();*/

LogicCalculator C = new LogicCalculator();

C.OR(8, 6);

C.printResult();


    }
}
